/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";

export namespace Components {
  interface PyroCode {
    highlightLines: string;
    language: string;
    lineNumbers: boolean;
    src: string;
  }
  interface PyroControls {}
  interface PyroMath {
    asciiMath: boolean;
    expression: string;
    inline: boolean;
  }
  interface PyroPresentation {
    options: object | string;
  }
  interface PyroProvider {
    state: { [key: string]: any };
  }
  interface PyroSlide {}
}

declare global {
  interface HTMLPyroCodeElement
    extends Components.PyroCode,
      HTMLStencilElement {}
  var HTMLPyroCodeElement: {
    prototype: HTMLPyroCodeElement;
    new (): HTMLPyroCodeElement;
  };

  interface HTMLPyroControlsElement
    extends Components.PyroControls,
      HTMLStencilElement {}
  var HTMLPyroControlsElement: {
    prototype: HTMLPyroControlsElement;
    new (): HTMLPyroControlsElement;
  };

  interface HTMLPyroMathElement
    extends Components.PyroMath,
      HTMLStencilElement {}
  var HTMLPyroMathElement: {
    prototype: HTMLPyroMathElement;
    new (): HTMLPyroMathElement;
  };

  interface HTMLPyroPresentationElement
    extends Components.PyroPresentation,
      HTMLStencilElement {}
  var HTMLPyroPresentationElement: {
    prototype: HTMLPyroPresentationElement;
    new (): HTMLPyroPresentationElement;
  };

  interface HTMLPyroProviderElement
    extends Components.PyroProvider,
      HTMLStencilElement {}
  var HTMLPyroProviderElement: {
    prototype: HTMLPyroProviderElement;
    new (): HTMLPyroProviderElement;
  };

  interface HTMLPyroSlideElement
    extends Components.PyroSlide,
      HTMLStencilElement {}
  var HTMLPyroSlideElement: {
    prototype: HTMLPyroSlideElement;
    new (): HTMLPyroSlideElement;
  };
  interface HTMLElementTagNameMap {
    "pyro-code": HTMLPyroCodeElement;
    "pyro-controls": HTMLPyroControlsElement;
    "pyro-math": HTMLPyroMathElement;
    "pyro-presentation": HTMLPyroPresentationElement;
    "pyro-provider": HTMLPyroProviderElement;
    "pyro-slide": HTMLPyroSlideElement;
  }
}

declare namespace LocalJSX {
  interface PyroCode {
    highlightLines?: string;
    language?: string;
    lineNumbers?: boolean;
    onInjectProps?: (event: CustomEvent<any>) => void;
    src?: string;
  }
  interface PyroControls {
    onNextSlide?: (event: CustomEvent<any>) => void;
    onPreviousSlide?: (event: CustomEvent<any>) => void;
    onToggleFullscreen?: (event: CustomEvent<any>) => void;
  }
  interface PyroMath {
    asciiMath?: boolean;
    expression?: string;
    inline?: boolean;
    onInjectProps?: (event: CustomEvent<any>) => void;
  }
  interface PyroPresentation {
    options?: object | string;
  }
  interface PyroProvider {
    state?: { [key: string]: any };
  }
  interface PyroSlide {
    onInjectProps?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    "pyro-code": PyroCode;
    "pyro-controls": PyroControls;
    "pyro-math": PyroMath;
    "pyro-presentation": PyroPresentation;
    "pyro-provider": PyroProvider;
    "pyro-slide": PyroSlide;
  }
}

export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "pyro-code": LocalJSX.PyroCode &
        JSXBase.HTMLAttributes<HTMLPyroCodeElement>;
      "pyro-controls": LocalJSX.PyroControls &
        JSXBase.HTMLAttributes<HTMLPyroControlsElement>;
      "pyro-math": LocalJSX.PyroMath &
        JSXBase.HTMLAttributes<HTMLPyroMathElement>;
      "pyro-presentation": LocalJSX.PyroPresentation &
        JSXBase.HTMLAttributes<HTMLPyroPresentationElement>;
      "pyro-provider": LocalJSX.PyroProvider &
        JSXBase.HTMLAttributes<HTMLPyroProviderElement>;
      "pyro-slide": LocalJSX.PyroSlide &
        JSXBase.HTMLAttributes<HTMLPyroSlideElement>;
    }
  }
}
