/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PyroPresentation {
    'author': string;
    'numbering': boolean;
    'presentationTitle': string;
    'subtitle': string;
  }
  interface PyroSlide {
    'slideTitle': string;
  }
}

declare global {


  interface HTMLPyroPresentationElement extends Components.PyroPresentation, HTMLStencilElement {}
  var HTMLPyroPresentationElement: {
    prototype: HTMLPyroPresentationElement;
    new (): HTMLPyroPresentationElement;
  };

  interface HTMLPyroSlideElement extends Components.PyroSlide, HTMLStencilElement {}
  var HTMLPyroSlideElement: {
    prototype: HTMLPyroSlideElement;
    new (): HTMLPyroSlideElement;
  };
  interface HTMLElementTagNameMap {
    'pyro-presentation': HTMLPyroPresentationElement;
    'pyro-slide': HTMLPyroSlideElement;
  }
}

declare namespace LocalJSX {
  interface PyroPresentation extends JSXBase.HTMLAttributes<HTMLPyroPresentationElement> {
    'author'?: string;
    'numbering'?: boolean;
    'presentationTitle'?: string;
    'subtitle'?: string;
  }
  interface PyroSlide extends JSXBase.HTMLAttributes<HTMLPyroSlideElement> {
    'slideTitle'?: string;
  }

  interface IntrinsicElements {
    'pyro-presentation': PyroPresentation;
    'pyro-slide': PyroSlide;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


