/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PyroPresentation {}
  interface PyroSlide {}
  interface PyroSlideContent {}
}

declare global {


  interface HTMLPyroPresentationElement extends Components.PyroPresentation, HTMLStencilElement {}
  var HTMLPyroPresentationElement: {
    prototype: HTMLPyroPresentationElement;
    new (): HTMLPyroPresentationElement;
  };

  interface HTMLPyroSlideElement extends Components.PyroSlide, HTMLStencilElement {}
  var HTMLPyroSlideElement: {
    prototype: HTMLPyroSlideElement;
    new (): HTMLPyroSlideElement;
  };

  interface HTMLPyroSlideContentElement extends Components.PyroSlideContent, HTMLStencilElement {}
  var HTMLPyroSlideContentElement: {
    prototype: HTMLPyroSlideContentElement;
    new (): HTMLPyroSlideContentElement;
  };
  interface HTMLElementTagNameMap {
    'pyro-presentation': HTMLPyroPresentationElement;
    'pyro-slide': HTMLPyroSlideElement;
    'pyro-slide-content': HTMLPyroSlideContentElement;
  }
}

declare namespace LocalJSX {
  interface PyroPresentation extends JSXBase.HTMLAttributes<HTMLPyroPresentationElement> {}
  interface PyroSlide extends JSXBase.HTMLAttributes<HTMLPyroSlideElement> {}
  interface PyroSlideContent extends JSXBase.HTMLAttributes<HTMLPyroSlideContentElement> {}

  interface IntrinsicElements {
    'pyro-presentation': PyroPresentation;
    'pyro-slide': PyroSlide;
    'pyro-slide-content': PyroSlideContent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


